name: Bug Report
description: Report a bug
title: 'bug: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to properly describe the bug.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: Clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: Clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: add_context
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem.
